@url = http://localhost:3550

### GET ALL PUBLISHER
GET {{url}}/publishers



### GET SINGLE PUBLISHER
GET {{url}}/publishers/65f034fd442fcd59fce48b8e


### ADD SINGLE PUBLISHER
POST {{url}}/publishers
Content-Type: application/json

{
    "name": "PhoenixBooks",
    "city": "Seoul",
    "description": "Sie sind ein Publisher mit Sitz in Seoul, Korea",
    "type": "publisher"
}

### UPDATE SINGLE PUBLISHER
PATCH {{url}}/publishers/65f074af6c3a06aeb104f6ad
Content-Type: application/json

{
    "type": "originalPublisher"
}

### DELETE SINGLE PUBLISHER
DELETE {{url}}/publishers/65f034fd442fcd59fce48b8e

### CLEAR PUBLISHER
DELETE {{url}}/publishers