@url = http://localhost:3550

### GET ALL USERS
GET {{url}}/users


### GET SINGLE USER
GET {{url}}/users/


### ADD SINGLE USER
POST {{url}}/users
Content-Type: application/json

{
    "userName": "melkuh",
    "email": "melkkuh@mail.de",
    "password": "23546",
    "accessGroups": ["administrators", "members", "loginUsers"],
    "age": 25
}

### ADD ANONYMOUS USER
POST {{url}}/users
content-type: application/json

{
    "userName": "anonymousUser",
    "password": "1234",
    "accessGroups": ["loggedOutUsers"]
}

### UPDATE SINGLE USER
PATCH {{url}}/users/660178b8ae9a190a2fff5ce0
Content-Type: application/json

{
    "accessGroups": ["adminstrators", "members"]
}

### GET CURRENT USER
GET {{url}}/users/current
Content-Type: application/json

{
    "userName": "anonymousUser",
    "password": "1234"
}

### DELETE SINGLE USER 
DELETE {{url}}/users/65f9116a9274dc8934b5eef9

### CLEAR USERS
DELETE {{url}}/users
