@url = http://localhost:3550

### GET ALL WEBTOON
GET {{url}}/webtoons



### GET SINGLE WEBTOON
GET {{url}}/webtoons/65f034fd442fcd59fce48b8e


### ADD SINGLE WEBTOON
POST {{url}}/webtoons
Content-Type: application/json

{
    "name": "Hasan AlSaid",
    "city": "Berlin",
    "description": "He writes queer stories"
}

### UPDATE SINGLE WEBTOON
PATCH {{url}}/webtoons/65f034fd442fcd59fce48b8e
Content-Type: application/json

{
    "name": "Hasan AlSaid",
    "city": "Berlin",
    "description": "He writes queer stories"
}

### DELETE SINGLE WEBTOON
DELETE {{url}}/webtoons/65f034fd442fcd59fce48b8e

### CLEAR WEBTOON
DELETE {{url}}/webtoons