@url = http://localhost:3550

### GET ALL WEBTOON
GET {{url}}/webtoons



### GET SINGLE WEBTOON
GET {{url}}/webtoons/65f7fe40f56d7ae57dabc625



### ADD SINGLE WEBTOON
POST {{url}}/webtoons
Content-Type: application/json

     {
        "titles": [{ "name": "Last Stand", "language": "English" }],
        "authors": [{ "name": "Park Min-Ji", "location": "South Korea" }],
        "artists": [{ "name": "Creative Hands", "location": "South Korea" }],
        "publisher": [
            {
                "name": "Tooniverse",
                "location": "South Korea",
                "description": "A leading webtoon platform",
                "type": "originalPublisher"
            }
        ],
        "status": { "abroadStatus": "running", "originalStatus": "running" },
        "chapters": 120,
        "genres": ["65f6364eedb904202f3cd738", "65f6364eedb904202f3cd747"],
        "type": "webtoon",
        "volume": 1,
        "price": { "value": "10,99", "currency": "€" },
        "pages": 180,
        "size": { "length": 9, "width": 3.5, "height": 19 },
        "isbn": "4567890123456",
        "translator": "Sophie Schmidt",
        "description": "A gripping love story set in the backdrop of a bustling city.",
        "ageRecommendation": 16
    }

### UPDATE SINGLE WEBTOON
PATCH {{url}}/webtoons/65f034fd442fcd59fce48b8e
Content-Type: application/json

{
    "name": "Hasan AlSaid",
    "city": "Berlin",
    "description": "He writes queer stories"
}

### DELETE SINGLE WEBTOON
DELETE {{url}}/webtoons/65f034fd442fcd59fce48b8e

### CLEAR WEBTOON
DELETE {{url}}/webtoons