@url = http://localhost:3550


### GET ALL AUTHORS
GET {{url}}/authors



### GET SINGLE AUTHOR
GET {{url}}/authors/65ef035167c34d6491ccdfab


### ADD SINGLE AUTHOR
POST {{url}}/authors
Content-Type: application/json

{
    "name": "Alex Hirschblume",
    "city": "Berlin",
    "description": "He writes children stories"
}

### UPDATE SINGLE AUTHOR
PATCH {{url}}/authors/65ef20bfc6e773ea61b1bcce
Content-Type: application/json

{
    "name": "Alexa Hirschblume",
    "description": "She writes queer stories"
}

### DELETE SINGLE AUTHOR
DELETE {{url}}/authors/65ef20bfc6e773ea61b1bcce

### CLEAR AUTHORS
DELETE {{url}}/authors